import type { PricingPlan } from "@/lib/pricing/types";
import { getSignupHref } from "@/lib/auth/roles";

/** Veritabanı boş veya erişilemez olduğunda landing fallback */
export const DEFAULT_PRICING_PLANS: PricingPlan[] = [
  {
    id: "default-esnaf-baslangic",
    segment: "esnaf",
    plan_key: "baslangic",
    name: "Başlangıç",
    description: "Dijital vitrininizi açın, müşterileriniz sizi bulsun.",
    price_monthly: 299,
    price_yearly: 2990,
    currency: "TRY",
    features: [
      "Dijital vitrin & mağaza sayfası",
      "Ürün & hizmet vitrini",
      "İletişim & konum haritası",
      "WhatsApp entegrasyonu",
    ],
    is_popular: false,
    is_active: true,
    sort_order: 0,
    cta_label: "Ücretsiz Dene",
    cta_href: getSignupHref("esnaf"),
  },
  {
    id: "default-esnaf-pro",
    segment: "esnaf",
    plan_key: "pro",
    name: "Pro",
    description: "Yerel SEO ve blog ile bölgenizde öne çıkın.",
    price_monthly: 599,
    price_yearly: 5990,
    currency: "TRY",
    features: [
      "Başlangıç paketindeki her şey",
      "Blog & yerel SEO araçları",
      "Profil gücü skor paneli",
      "2. el cihaz pazaryeri vitrini",
      "Teknik servis sayfası",
      "Öncelikli destek",
    ],
    is_popular: true,
    is_active: true,
    sort_order: 1,
    cta_label: "Pro'ya Geç",
    cta_href: getSignupHref("esnaf"),
  },
  {
    id: "default-esnaf-isletme",
    segment: "esnaf",
    plan_key: "isletme",
    name: "İşletme",
    description: "Çok şubeli ve yoğun işletmeler için tam paket.",
    price_monthly: 999,
    price_yearly: 9990,
    currency: "TRY",
    features: [
      "Pro paketindeki her şey",
      "Gelişmiş analitik & raporlar",
      "Çoklu personel erişimi",
      "Özel alan adı desteği",
      "Dedicated hesap yöneticisi",
    ],
    is_popular: false,
    is_active: true,
    sort_order: 2,
    cta_label: "İletişime Geç",
    cta_href: getSignupHref("esnaf"),
  },
  {
    id: "default-toptanci-baslangic",
    segment: "toptanci",
    plan_key: "baslangic",
    name: "Başlangıç",
    description: "XML stok besleme ile esnafa anında ulaşın.",
    price_monthly: 499,
    price_yearly: 4990,
    currency: "TRY",
    features: [
      "XML stok besleme paneli",
      "Toptancı vitrin sayfası",
      "Sipariş bildirimleri",
      "Temel stok senkronizasyonu",
    ],
    is_popular: false,
    is_active: true,
    sort_order: 0,
    cta_label: "Başvur",
    cta_href: getSignupHref("toptanci"),
  },
  {
    id: "default-toptanci-pro",
    segment: "toptanci",
    plan_key: "pro",
    name: "Pro",
    description: "Geniş esnaf ağına hızlı ve güvenilir tedarik.",
    price_monthly: 999,
    price_yearly: 9990,
    currency: "TRY",
    features: [
      "Başlangıç paketindeki her şey",
      "Çoklu XML kaynağı",
      "Otomatik fiyat güncelleme",
      "Cari & sipariş yönetimi",
      "Performans raporları",
      "Öncelikli API erişimi",
    ],
    is_popular: true,
    is_active: true,
    sort_order: 1,
    cta_label: "Pro'ya Geç",
    cta_href: getSignupHref("toptanci"),
  },
  {
    id: "default-toptanci-kurumsal",
    segment: "toptanci",
    plan_key: "kurumsal",
    name: "Kurumsal",
    description: "Bölgesel ve ulusal dağıtım ağları için.",
    price_monthly: 1999,
    price_yearly: 19990,
    currency: "TRY",
    features: [
      "Pro paketindeki her şey",
      "Sınırsız XML endpoint",
      "Özel entegrasyon desteği",
      "SLA garantili uptime",
      "Kurumsal faturalandırma",
    ],
    is_popular: false,
    is_active: true,
    sort_order: 2,
    cta_label: "Teklif Al",
    cta_href: getSignupHref("toptanci"),
  },
];
