/** Cihaz Al — Akıllı Saat marka / model hapis listeleri */

export const WATCH_BRANDS = [
  "Apple Watch",
  "Huawei",
  "Honor",
  "Samsung",
  "Xiaomi",
  "Garmin",
] as const;

export type WatchBrand = (typeof WATCH_BRANDS)[number];

export const WATCH_MODELS_BY_BRAND: Record<WatchBrand, readonly string[]> = {
  "Apple Watch": [
    "Series 1",
    "Series 2",
    "Series 3",
    "Series 4",
    "Series 5",
    "Series 6",
    "Series 7",
    "Series 8",
    "Series 9",
    "Series 10",
    "Series 11",
    "SE (1. Nesil)",
    "SE (2. Nesil)",
    "SE (3. Nesil)",
    "Ultra",
    "Ultra 2",
    "Ultra 3",
  ],
  Samsung: [
    "Fit 2",
    "Fit 2 Pro",
    "Fit 3",
    "Galaxy Gear",
    "Galaxy Watch",
    "Galaxy Watch 3",
    "Galaxy Watch 4",
    "Galaxy Watch 4 Classic",
    "Galaxy Watch 5",
    "Galaxy Watch 5 Pro",
    "Galaxy Watch 6",
    "Galaxy Watch 6 Classic",
    "Galaxy Watch 6 Classic Astro Edition",
    "Galaxy Watch 7",
    "Galaxy Watch 8",
    "Galaxy Watch 8 Classic",
    "Galaxy Watch Active",
    "Galaxy Watch Active 2",
    "Galaxy Watch Ultra",
    "Gear 2",
    "Gear 2 Neo",
    "Gear Live",
    "Gear S",
    "Gear S2",
    "Gear S2 Classic",
    "Gear S3 Classic",
    "Gear S3 Frontier",
    "Gear Sport",
    "S9110",
  ],
  Garmin: [
    "Approach",
    "D2 Bravo",
    "D2 Charlie",
    "D2 Delta",
    "Descent",
    "Epix",
    "Fenix",
    "Forerunner",
    "Instinct",
    "Marq",
    "Quatix",
    "Swim",
    "Tactix",
    "Venu Sq",
    "Vivoactive",
    "Vivofit",
    "Vivomove",
  ],
  Xiaomi: [
    "Black Shark GS3 Ultra",
    "Mi Watch",
    "Mi Watch Color Sports",
    "Mi Watch Lite",
    "Mi Watch Revolve",
    "Mi Watch Revolve Active",
    "Poco Watch",
    "Redmi Watch",
    "Redmi Watch 2",
    "Redmi Watch 2 Lite",
    "Redmi Watch 3",
    "Redmi Watch 3 Active",
    "Redmi Watch 4",
    "Redmi Watch 5",
    "Redmi Watch 5 Lite",
    "Redmi Watch 6",
    "Redmi Watch Move",
    "Smart Band 8",
    "Smart Band 8 Active",
    "Smart Band 8 Pro",
    "Smart Band 9 Pro",
    "Watch 2",
    "Watch 2 Pro",
    "Watch 5",
    "Watch Color",
    "Watch Color 2",
    "Watch S1",
    "Watch S1 Active",
    "Watch S1 Pro",
    "Watch S2",
    "Watch S3",
    "Watch S4",
  ],
  Honor: [
    "Choice Watch",
    "MagicWatch 2",
    "Watch 4",
    "Watch 4 Pro",
    "Watch 5",
    "Watch 5 Pro",
    "Watch 5 Ultra",
    "Watch ES",
    "Watch GS 3",
    "Watch GS 4",
    "Watch GS 5",
    "Watch GS Pro",
    "Watch X5",
    "Watch X5i",
  ],
  Huawei: [
    "Children's Watch 4X",
    "Fit",
    "GT 6 Pro",
    "Watch",
    "Watch 2",
    "Watch 2 2018",
    "Watch 2 Classic",
    "Watch 2 Pro",
    "Watch 3",
    "Watch 3 Pro",
    "Watch 4",
    "Watch 4 Pro",
    "Watch 4 Pro Space Exploration",
    "Watch 5",
    "Watch Buds",
    "Watch Buds 2",
    "Watch D",
    "Watch D2",
    "Watch Fit",
    "Watch Fit 2",
    "Watch Fit 3",
    "Watch Fit 4",
    "Watch Fit 4 Pro",
    "Watch Fit 5",
    "Watch Fit 5 Pro",
    "Watch Fit Elegant",
    "Watch Fit mini",
    "Watch GT",
    "Watch GT 2",
    "Watch GT 2e",
    "Watch GT 2 Porsche Design",
    "Watch GT 2 Pro",
    "Watch GT 3",
    "Watch GT 3 Porsche Design",
    "Watch GT 3 Pro",
    "Watch GT 3 SE",
    "Watch GT 4",
    "Watch GT 5",
    "Watch GT 5 Pro",
    "Watch GT 6",
    "Watch GT 6 Pro",
    "Watch GT Cyber",
    "Watch GT Runner",
    "Watch GT Runner 2",
    "Watch Magic",
    "Watch Ultimate",
    "Watch Ultimate 2",
    "Watch Ultimate Design",
    "Watch Ultimate Design Spring Edition",
  ],
};

export const WATCH_CASE_DIAMETER_OPTIONS = [
  "38 mm",
  "40 mm",
  "41 mm",
  "42 mm",
  "43 mm",
  "44 mm",
  "45 mm",
  "46 mm",
  "47 mm",
  "48 mm",
  "49 mm",
  "50 mm ve Üzeri",
] as const;

export const WATCH_COLOR_OPTIONS = [
  "Altın",
  "Beyaz",
  "Bordo",
  "Gri",
  "Gümüş",
  "Kahverengi",
  "Kırmızı",
  "Lacivert",
  "Mavi",
  "Mor",
  "Pembe",
  "Sarı",
  "Siyah",
  "Turuncu",
  "Yeşil",
  "Karışık Renkli",
] as const;

export const WATCH_CASE_MATERIAL_OPTIONS = [
  "Alüminyum",
  "Paslanmaz Çelik",
  "Seramik",
  "Titanyum",
] as const;

export function getWatchModelsForBrand(brand: string): readonly string[] {
  if (!brand) return [];
  return WATCH_MODELS_BY_BRAND[brand as WatchBrand] ?? [];
}
